name: Python CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.12
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run mypy
        run: |
          pip install mypy
          mypy **/*.py
      - name: Run flake8
        run: |
          pip install flake8
          flake8 **/*.py
      - name: Check run_me.py
        run: |
          python run_me.py